services:
  - type: web
    name: video-downloader
    runtime: node
    plan: free
    region: singapore
    buildCommand: bash -c "apt-get update && apt-get install -y ffmpeg python3 python3-pip && pip3 install yt-dlp && npm install"
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: YTDLP_PATH
        value: yt-dlp
      - key: FFMPEG_PATH
        value: ffmpeg
      - key: NODE_ENV
        value: production
